//go:build ignore

// Regenerate with: go generate ./internal/baseimage
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"path"
	"sort"
	"strings"
	"time"
)

type releaseManifest struct {
	Version string `json:"version"`
	Images  map[string]struct {
		URL    string `json:"url"`
		SHA256 string `json:"sha256"`
		Size   int64  `json:"size"`
	} `json:"images"`
}

func main() {
	tag := flag.String("tag", "", "published base-image release tag")
	flag.Parse()
	if *tag == "" || strings.ContainsAny(*tag, "/\\") {
		panic("a release tag is required")
	}
	url := "https://github.com/Lullabot/sandbar/releases/download/" + *tag + "/manifest.json"
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		panic(fmt.Sprintf("fetching manifest: HTTP %s", resp.Status))
	}
	var manifest releaseManifest
	if err := json.NewDecoder(resp.Body).Decode(&manifest); err != nil {
		panic(err)
	}
	if manifest.Version != *tag || len(manifest.Images) != 2 {
		panic("release manifest version or architecture set is unexpected")
	}
	keys := make([]string, 0, len(manifest.Images))
	for arch := range manifest.Images {
		if arch != "amd64" && arch != "arm64" {
			panic("unsupported release architecture: " + arch)
		}
		keys = append(keys, arch)
	}
	sort.Strings(keys)
	var src strings.Builder
	fmt.Fprintln(&src, "// Code generated by go generate ./internal/baseimage; DO NOT EDIT.")
	fmt.Fprintln(&src, "package baseimage")
	fmt.Fprintf(&src, "var PinnedManifest = Manifest{Version: %q, Images: map[string]ImageEntry{\n", manifest.Version)
	for _, arch := range keys {
		entry := manifest.Images[arch]
		filename := path.Base(entry.URL)
		if !strings.HasPrefix(entry.URL, "https://github.com/Lullabot/sandbar/releases/download/"+*tag+"/") ||
			filename != fmt.Sprintf("sandbar-base-debian-13-%s.qcow2", arch) ||
			len(entry.SHA256) != 64 || strings.Trim(entry.SHA256, "0123456789abcdef") != "" || entry.Size <= 0 {
			panic("invalid release entry for " + arch)
		}
		fmt.Fprintf(&src, "%q: {URL: %q, Filename: %q, SHA256: %q, Size: %d},\n", arch, entry.URL, filename, entry.SHA256, entry.Size)
	}
	fmt.Fprintln(&src, "}}")
	formatted, err := format.Source([]byte(src.String()))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("manifest_generated.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
