// Code generated by go generate ./internal/baseimage; DO NOT EDIT.
package baseimage

var PinnedManifest = Manifest{Version: "base-image-2026.09.29.164715", Images: map[string]ImageEntry{
	"amd64": {URL: "https://github.com/Lullabot/sandbar/releases/download/base-image-2026.09.29.164715/sandbar-base-debian-13-amd64.qcow2", Filename: "sandbar-base-debian-13-amd64.qcow2", SHA256: "1db1103bf8095f03ac383b226653087f0eaef9d3d235d8c7ee6fc155b770d5bf", Size: 1007550464},
	"arm64": {URL: "https://github.com/Lullabot/sandbar/releases/download/base-image-2026.09.29.164715/sandbar-base-debian-13-arm64.qcow2", Filename: "sandbar-base-debian-13-arm64.qcow2", SHA256: "81031834a776961eb94a5cb4a8f716060d1540799110fd4cd5d33cd4859e982b", Size: 975241216},
}}
