// Code generated by go generate ./internal/baseimage; DO NOT EDIT.
package baseimage

var PinnedManifest = Manifest{Version: "base-image-2026.09.29.151245", Images: map[string]ImageEntry{
	"amd64": {URL: "https://github.com/Lullabot/sandbar/releases/download/base-image-2026.09.29.151245/sandbar-base-debian-13-amd64.qcow2", Filename: "sandbar-base-debian-13-amd64.qcow2", SHA256: "20813c0d17cd67c81dd96535285701a9415d519931059813c6d80f27719196db", Size: 1006632960},
	"arm64": {URL: "https://github.com/Lullabot/sandbar/releases/download/base-image-2026.09.29.151245/sandbar-base-debian-13-arm64.qcow2", Filename: "sandbar-base-debian-13-arm64.qcow2", SHA256: "167d4d06cdadfaf909eced145cf744018d901153e2a181c09e2291989dfc249e", Size: 974258176},
}}
