package ui

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"sync"
	"testing"

	"github.com/lullabot/sandbar/internal/browse"
	"github.com/lullabot/sandbar/internal/lima"
)

// copyArgsRunner records the argv of the `limactl copy` it is asked to stream, so
// a test can assert on the endpoints the UI actually hands to limactl rather than
// on an intermediate the UI computes and might not use.
type copyArgsRunner struct {
	mu   sync.Mutex
	args []string
}

func (r *copyArgsRunner) Output(context.Context, ...string) ([]byte, error) { return nil, nil }

func (r *copyArgsRunner) Stream(_ context.Context, _ io.Reader, _ io.Writer, args ...string) error {
	if len(args) > 0 && args[0] == "copy" {
		r.mu.Lock()
		r.args = append([]string(nil), args...)
		r.mu.Unlock()
	}
	return nil
}

func (r *copyArgsRunner) StreamOut(_ context.Context, _ io.Reader, _ io.Writer, _ ...string) error {
	return nil
}

func (r *copyArgsRunner) seen() []string {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.args
}

// guestUser must read the real guest login account from Lima's ssh.config — Lima
// can name the guest account differently from the host user (e.g. "andrew.guest"),
// and that account is what limactl copy/shell authenticate as. A missing or
// unreadable ssh.config yields "" so the caller can fall back to the host guess.
func TestGuestUserFromSSHConfig(t *testing.T) {
	dir := t.TempDir()
	cfg := "# generated by lima\nHost lima-zoom\n  IdentityFile \"/x/user\"\n  User andrew.guest\n  Hostname 127.0.0.1\n  Port 60022\n"
	if err := os.WriteFile(filepath.Join(dir, "ssh.config"), []byte(cfg), 0o644); err != nil {
		t.Fatal(err)
	}
	if got := guestUser(dir); got != "andrew.guest" {
		t.Fatalf("guestUser = %q, want %q (the ssh.config User, not the host user)", got, "andrew.guest")
	}

	// No ssh.config in the dir → "" (caller falls back to the host guess).
	if got := guestUser(t.TempDir()); got != "" {
		t.Fatalf("guestUser(dir without ssh.config) = %q, want empty", got)
	}
	// Empty dir → "".
	if got := guestUser(""); got != "" {
		t.Fatalf("guestUser(\"\") = %q, want empty", got)
	}
}

// guestHome reads the guest home from Lima's cloud-config.yaml. Lima places the
// home at /home/<user>.guest (not /home/<user>), so it can't be derived from the
// username — this is the value the transfer flow must use for the destination
// default and the download start dir. A bare "default" entry in the users list
// must be skipped, and a missing cloud-config yields "" so the caller falls back.
func TestGuestHomeFromCloudConfig(t *testing.T) {
	dir := t.TempDir()
	// ssh.config sets the login user, so guestHome prefers that user's entry.
	ssh := "Host lima-x\n  User andrew\n  Port 60022\n"
	if err := os.WriteFile(filepath.Join(dir, "ssh.config"), []byte(ssh), 0o644); err != nil {
		t.Fatal(err)
	}
	cc := "#cloud-config\nusers:\n  - default\n  - name: \"andrew\"\n    uid: \"1000\"\n    homedir: \"/home/andrew.guest\"\n    shell: /bin/bash\n"
	if err := os.WriteFile(filepath.Join(dir, "cloud-config.yaml"), []byte(cc), 0o644); err != nil {
		t.Fatal(err)
	}
	if got := guestHome(dir); got != "/home/andrew.guest" {
		t.Fatalf("guestHome = %q, want /home/andrew.guest (Lima places the home at /home/<user>.guest)", got)
	}

	// No cloud-config → "" so the caller falls back to the /home/<user> guess.
	if got := guestHome(t.TempDir()); got != "" {
		t.Fatalf("guestHome(no cloud-config) = %q, want empty", got)
	}
	if got := guestHome(""); got != "" {
		t.Fatalf("guestHome(\"\") = %q, want empty", got)
	}
}

// The destination handed to limactl is the directory the user picked, VERBATIM —
// for a directory source exactly as for a file. lima.Copy places the source INSIDE
// the destination (scp's semantics, and why that backend is pinned), so appending
// the source's basename here would nest a directory one level too deep the moment
// the destination already contained it: a re-upload of mydir landing in
// dest/mydir/mydir. That appending is what this test replaced.
func TestTransferDestIsTheUsersDirectoryVerbatim(t *testing.T) {
	cases := []struct {
		name             string
		upload           bool
		recursive        bool
		destDir, srcPath string
		wantSrc, wantDst string
	}{
		{
			name: "upload a directory", upload: true, recursive: true,
			destDir: "/home/a.guest/proj", srcPath: "/Users/a/work/mydir",
			wantSrc: "/Users/a/work/mydir", wantDst: "web:/home/a.guest/proj",
		},
		{
			name: "download a directory", upload: false, recursive: true,
			destDir: "/Users/a/dl", srcPath: "/home/a.guest/proj/mydir",
			wantSrc: "web:/home/a.guest/proj/mydir", wantDst: "/Users/a/dl",
		},
		{
			name: "upload a file", upload: true, recursive: false,
			destDir: "/home/a.guest/proj", srcPath: "/Users/a/work/notes.txt",
			wantSrc: "/Users/a/work/notes.txt", wantDst: "web:/home/a.guest/proj",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			rec := &copyArgsRunner{}
			m := newTestModelWithCli(t, lima.New(rec))
			m.view = viewDest
			m.transferVM = "web"
			m.transferSrc = tc.srcPath
			m.transferUpload = tc.upload
			m.transferRecursive = tc.recursive
			m.dest, _ = browse.NewDestInput("Destination dir: ", tc.destDir, nil)

			after, cmd := m.Update(ctrlKey('s'))
			m = after.(model)
			l := newTeaLoop(t, m)
			l.exec(cmd)
			l.pump("the copy to reach limactl", func(model) bool { return rec.seen() != nil })

			args := rec.seen()
			src, dst := args[len(args)-2], args[len(args)-1]
			if src != tc.wantSrc || dst != tc.wantDst {
				t.Fatalf("limactl copy endpoints = (%q, %q), want (%q, %q)\nfull argv: %v",
					src, dst, tc.wantSrc, tc.wantDst, args)
			}
		})
	}
}
