package lima

import (
	"os"
	"path/filepath"
	"testing"
)

// GuestUser must read the real guest login account from Lima's ssh.config — Lima
// can name the guest account differently from the host user (e.g. "andrew.guest"),
// and that account is what limactl copy/shell authenticate as. A missing or
// unreadable ssh.config yields "" so the caller can fall back to the host guess.
func TestGuestUserFromSSHConfig(t *testing.T) {
	dir := t.TempDir()
	cfg := "# generated by lima\nHost lima-zoom\n  IdentityFile \"/x/user\"\n  User andrew.guest\n  Hostname 127.0.0.1\n  Port 60022\n"
	if err := os.WriteFile(filepath.Join(dir, "ssh.config"), []byte(cfg), 0o644); err != nil {
		t.Fatal(err)
	}
	if got := GuestUser(dir); got != "andrew.guest" {
		t.Fatalf("guestUser = %q, want %q (the ssh.config User, not the host user)", got, "andrew.guest")
	}

	// No ssh.config in the dir → "" (caller falls back to the host guess).
	if got := GuestUser(t.TempDir()); got != "" {
		t.Fatalf("GuestUser(dir without ssh.config) = %q, want empty", got)
	}
	// Empty dir → "".
	if got := GuestUser(""); got != "" {
		t.Fatalf("GuestUser(\"\") = %q, want empty", got)
	}
}

// GuestHome reads the guest home from Lima's cloud-config.yaml. Lima places the
// home at /home/<user>.guest (not /home/<user>), so it can't be derived from the
// username — this is the value the transfer flow must use for the destination
// default and the download start dir. A bare "default" entry in the users list
// must be skipped, and a missing cloud-config yields "" so the caller falls back.
func TestGuestHomeFromCloudConfig(t *testing.T) {
	dir := t.TempDir()
	// ssh.config sets the login user, so guestHome prefers that user's entry.
	ssh := "Host lima-x\n  User andrew\n  Port 60022\n"
	if err := os.WriteFile(filepath.Join(dir, "ssh.config"), []byte(ssh), 0o644); err != nil {
		t.Fatal(err)
	}
	cc := "#cloud-config\nusers:\n  - default\n  - name: \"andrew\"\n    uid: \"1000\"\n    homedir: \"/home/andrew.guest\"\n    shell: /bin/bash\n"
	if err := os.WriteFile(filepath.Join(dir, "cloud-config.yaml"), []byte(cc), 0o644); err != nil {
		t.Fatal(err)
	}
	if got := GuestHome(dir); got != "/home/andrew.guest" {
		t.Fatalf("guestHome = %q, want /home/andrew.guest (Lima places the home at /home/<user>.guest)", got)
	}

	// No cloud-config → "" so the caller falls back to the /home/<user> guess.
	if got := GuestHome(t.TempDir()); got != "" {
		t.Fatalf("GuestHome(no cloud-config) = %q, want empty", got)
	}
	if got := GuestHome(""); got != "" {
		t.Fatalf("GuestHome(\"\") = %q, want empty", got)
	}
}
