package provision

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lullabot/sandbar/internal/lima"
	"github.com/lullabot/sandbar/internal/vm"
)

// limaInstanceYAML is a lima 2.1.3 instance file, copied from a real base image
// this repository built (~/.lima/sandbar-base/lima.yaml). It is the ground truth
// readBaseOverlay has to read: Lima keeps the overlay it was handed — comments,
// mount block, provision script and all — so what is below is exactly what
// RenderBaseOverlay emitted on the day that base was created, and exactly what
// `limactl start` will apply to it again today.
//
// Note the bootstrap script: it installs `ansible`, and checks only for ansible and
// rsync. The current overlay installs ansible-core, curl and gnupg, because the base
// role now shells out to `gpg --dearmor` and its comments name those tools as
// "guaranteed present by the Lima dependency script". A base created under the old
// script does not carry that guarantee — which is why an overlay this stale must be
// rebuilt, not converged.
const limaInstanceYAML = `# Generated by the Claude Code VM TUI — inherits the shipped Debian 13 image
# template so Lima manages image selection, arch, and caching.
cpus: 8
memory: "8GiB"
disk: "20GiB"
mounts:
- location: "/home/debian/sandbar/.claude/worktrees/multi-shell-tmux"
  mountPoint: /mnt/playbook
  writable: false
provision:
- mode: dependency
  script: |
    #!/bin/bash
    set -eux -o pipefail
    if command -v ansible >/dev/null 2>&1 && command -v rsync >/dev/null 2>&1; then
      exit 0
    fi
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y ansible rsync
`

// writeInstanceYAML materialises a Lima instance file for baseName under a private
// LIMA_HOME, the way a real base image's would sit on disk.
func writeInstanceYAML(t *testing.T, baseName, content string) {
	t.Helper()
	home := t.TempDir()
	t.Setenv("LIMA_HOME", home)
	dir := filepath.Join(home, baseName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "lima.yaml"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestReadBaseOverlayReadsTheInstanceFile: the base's mount and bootstrap are read
// from the instance's own lima.yaml, because that file — not this process's idea of
// where the playbook lives or what the bootstrap installs — is what Lima applies
// when the base is started for a re-apply.
func TestReadBaseOverlayReadsTheInstanceFile(t *testing.T) {
	writeInstanceYAML(t, "sandbar-base", limaInstanceYAML)

	got, ok := readBaseOverlay(lima.LocalFiles(), "sandbar-base")
	if !ok {
		t.Fatal("readBaseOverlay could not read the base's instance file")
	}
	if want := "/home/debian/sandbar/.claude/worktrees/multi-shell-tmux"; got.PlaybookDir != want {
		t.Errorf("PlaybookDir = %q, want %q", got.PlaybookDir, want)
	}
	if got.Bootstrap == "" || !strings.Contains(got.Bootstrap, "apt-get install -y ansible rsync") {
		t.Errorf("Bootstrap did not come through:\n%s", got.Bootstrap)
	}
}

// TestReadBaseOverlayAbsentInstance: no instance (or no readable lima.yaml) means we
// cannot prove what the base would do, which the caller must treat as "do not
// converge" — never as "converge anyway".
func TestReadBaseOverlayAbsentInstance(t *testing.T) {
	t.Setenv("LIMA_HOME", t.TempDir())
	if o, ok := readBaseOverlay(lima.LocalFiles(), "sandbar-base"); ok {
		t.Fatalf("readBaseOverlay on an absent instance returned %+v, ok=true", o)
	}
}

// TestBaseOverlayReaderUnderstandsTheOverlayWeWrite pins the reader to the writer.
// RenderBaseOverlay decides what a base mounts and what its bootstrap installs, and
// Lima preserves both blocks verbatim in the instance file. If the overlay's shape
// ever changes and this reader is not changed with it, the reader would quietly stop
// recognising sand's own base images — and every stale create would fall back to a
// from-scratch rebuild, with nothing to show why.
func TestBaseOverlayReaderUnderstandsTheOverlayWeWrite(t *testing.T) {
	const dir = "/home/andrew/sandbar"
	overlay, err := RenderBaseOverlay(vm.DefaultCreateConfig(), dir)
	if err != nil {
		t.Fatalf("RenderBaseOverlay: %v", err)
	}
	got, ok := parseBaseOverlay(overlay)
	if !ok {
		t.Fatalf("the reader does not recognise the overlay we write:\n%s", overlay)
	}
	if got.PlaybookDir != dir {
		t.Errorf("PlaybookDir = %q, want %q", got.PlaybookDir, dir)
	}
	if !strings.Contains(got.Bootstrap, "apt-get install -y") {
		t.Errorf("the bootstrap script did not come through:\n%q", got.Bootstrap)
	}
}

// TestBaseConvergeable covers the whole decision: a base may only be converged in
// place when it was created from the same overlay this create would use.
func TestBaseConvergeable(t *testing.T) {
	// The instance file of a base created from the CURRENT overlay, mounting the
	// current playbook directory — the only case that may be converged.
	dir := t.TempDir()
	current, err := RenderBaseOverlay(vm.DefaultCreateConfig(), dir)
	if err != nil {
		t.Fatalf("RenderBaseOverlay: %v", err)
	}

	// Same overlay, but the base mounts a different checkout (a git worktree, or the
	// temp dir a previous run of a released binary extracted the playbook into).
	otherDir := t.TempDir()
	foreignMount, err := RenderBaseOverlay(vm.DefaultCreateConfig(), otherDir)
	if err != nil {
		t.Fatalf("RenderBaseOverlay: %v", err)
	}

	// The RIGHT playbook, mounted where we expect it — but a base created by an older
	// sand, whose bootstrap script never installed the tools today's playbook shells
	// out to. This isolates the bootstrap half of the check: everything else about
	// this instance matches.
	oldBootstrap := "mounts:\n- location: \"" + dir + "\"\n  mountPoint: /mnt/playbook\n  writable: false\n" +
		"provision:\n- mode: dependency\n  script: |\n    #!/bin/bash\n    apt-get install -y ansible rsync\n"

	for _, tc := range []struct {
		name     string
		instance string
		want     bool
	}{
		{"same overlay, same playbook", string(current), true},
		{"a different playbook directory", string(foreignMount), false},
		{"the right playbook, an older bootstrap", oldBootstrap, false},
		{"an older sand's base entirely", limaInstanceYAML, false},
		{"no instance file at all", "", false},
		{"an unreadable instance file", "\x00not yaml: [", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if tc.instance == "" {
				t.Setenv("LIMA_HOME", t.TempDir())
			} else {
				writeInstanceYAML(t, "sandbar-base", tc.instance)
			}
			p := &Provisioner{PlaybookDir: dir}
			got, why := p.baseConvergeable(vm.DefaultCreateConfig())
			if got != tc.want {
				t.Fatalf("baseConvergeable = %v (%s), want %v", got, why, tc.want)
			}
			if !got && why == "" {
				t.Error("a base that cannot be converged must say why — the user has to know what the rebuild is for")
			}
		})
	}
}

// TestSameDirMatchesThroughASymlink: the comparison is between two host paths for
// the same directory, so it must survive the ways one directory can be spelled —
// notably macOS, where the per-process temp dir the embedded playbook is extracted
// into is reached through a symlink. A false mismatch only costs a rebuild, but it
// would cost one on every single create.
func TestSameDirMatchesThroughASymlink(t *testing.T) {
	real := t.TempDir()
	link := filepath.Join(t.TempDir(), "link")
	if err := os.Symlink(real, link); err != nil {
		t.Fatal(err)
	}
	if !sameDir(real, link) {
		t.Errorf("sameDir(%q, %q) = false, want true (same directory, different path)", real, link)
	}
	if sameDir(real, filepath.Join(real, "..")) {
		t.Error("sameDir must not match a different directory")
	}
	if sameDir("/nonexistent/a", "/nonexistent/b") {
		t.Error("sameDir must not match two paths that do not exist")
	}
	if !sameDir("/nonexistent/a", "/nonexistent/a/") {
		t.Error("sameDir must match one path spelled two ways, even if it does not exist")
	}
	if sameDir("", "") {
		t.Error("sameDir must not match two empty paths — an unknown mount is not a match")
	}
}
