package provision

import (
	"fmt"
	"strings"

	"github.com/lullabot/sandbar/internal/vm"
)

// overlayHeader is the fixed top of the base overlay. The image entry is
// supplied separately after its bytes have been verified on the Lima host.
const overlayHeader = `# Generated by sand from its verified, published base image. The default
# host-home mount is intentionally NOT inherited (agents run unsupervised in
# these VMs). The only mount is the playbook, read-only: there is NO writable
# host mount, so deleting a VM provably removes everything it produced. Move
# files in or out with the TUI's Upload/Download actions.
`

// overlayContainerd switches off Lima's own container stack. Lima defaults to
// installing the nerdctl-full bundle and running rootless containerd for the
// user, which is redundant here: the published image already carries Docker,
// and that is the container runtime these VMs use.
//
// It is not free. Measured on a clone of the base (qemu/x86_64, 8 vCPU), Lima's
// containerd setup runs inside cloud-final on EVERY boot and costs ~19s of the
// ~58s `limactl start` — cloud-final alone drops from 13.3s to 3.5s with this
// off, and a clone's boot goes 58s -> 39s. It also plants ~575MB of nerdctl-full
// in /usr/local/bin of the BASE image, which every clone then copies.
//
// Lima's boot script skips the whole stage when both are false; docker.service
// is untouched (verified: docker info/ps still work on a base built this way).
const overlayContainerd = `containerd:
  system: false
  user: false
`

// overlayProvision is the idempotent dependency bootstrap for finalize. Its
// guard finds these packages in the published image and exits on normal boots;
// the install arm keeps a non-baked image usable if one is supplied later.
const overlayProvision = `provision:
- mode: dependency
  script: |
    #!/bin/bash
    set -eux -o pipefail
    # Install just enough to run the playbook over ` + "`limactl shell`" + `; skip the
    # apt work once present so restarts stay fast. The playbook itself is run
    # separately (over a shell) so its output is visible. This script reruns on
    # every boot (including every clone's), so the guard must check for every
    # tool it installs or a stale check will leave later boots missing one.
    if command -v ansible-playbook >/dev/null 2>&1 \
       && command -v rsync >/dev/null 2>&1 \
       && command -v curl >/dev/null 2>&1 \
       && command -v gpg >/dev/null 2>&1 \
       && python3 -c 'import passlib' >/dev/null 2>&1; then
      exit 0
    fi
    export DEBIAN_FRONTEND=noninteractive
    # apt_retry rides out the VM's first-boot apt work (apt-daily /
    # unattended-upgrades): this script can run before that has released the apt
    # locks, and DPkg::Lock::Timeout does NOT cover apt-get update's
    # /var/lib/apt/lists/lock, so a timeout-guarded update still dies with "Could
    # not get lock ... held by process N". Retry the whole step until the locks
    # free (40 * 15s = 10 min ceiling), then fail loudly.
    apt_retry() {
      n=0
      until "$@"; do
        n=$((n + 1))
        if [ "$n" -ge 40 ]; then
          echo "apt: still locked after $n attempts, giving up" >&2
          return 1
        fi
        echo "apt: locked by the VM's first-boot apt, retry $n/40..." >&2
        sleep 15
      done
    }
    apt_retry apt-get -o DPkg::Lock::Timeout=60 update
    # --no-install-recommends is load-bearing, not hygiene: Debian's ansible-core
    # Recommends: ansible, so without it apt pulls the very 200MB collection
    # bundle (~436MB of ansible_collections on disk) that installing ansible-core
    # instead of ansible exists to avoid. Dropping this flag silently restores
    # the fat bundle and the slim-bootstrap win with it.
    #
    # python3-passlib is what --no-install-recommends costs us: the user role
    # hashes the generated account password with the password_hash('sha512')
    # filter, which imports passlib at runtime. The fat ansible bundle used to
    # pull it in as a Recommends, so dropping the bundle broke the play with
    # "Unable to encrypt nor hash, passlib must be installed". Name it
    # explicitly rather than leaning on another package's recommendation.
    apt_retry apt-get -o DPkg::Lock::Timeout=60 install -y --no-install-recommends ansible-core rsync curl gnupg ca-certificates python3-passlib
`

// BaseImageSpec identifies one verified image file on the host running limactl.
// Arch uses Lima's spelling, not Go's architecture names.
type BaseImageSpec struct {
	Location string
	Arch     string
	Digest   string
}

// RenderBaseOverlay produces the Lima overlay for the verified image. The
// published Debian cloud kernel lacks 9p modules, so reverse-sshfs is required
// for the read-only playbook mount used by finalize. Lima prepares sshfs on the
// first boot and reuses it on clones.
//
// The only host mount is read-only. Client.Configure still strips any writable
// mount a clone inherits as a standing guard.
func RenderBaseOverlay(cfg vm.CreateConfig, playbookDir string, image BaseImageSpec) ([]byte, error) {
	digest := strings.TrimPrefix(image.Digest, "sha256:")
	if image.Location == "" || (image.Arch != "x86_64" && image.Arch != "aarch64") ||
		!strings.HasPrefix(image.Digest, "sha256:") || len(digest) != 64 || strings.Trim(digest, "0123456789abcdef") != "" {
		return nil, fmt.Errorf("incomplete Lima base image specification")
	}
	var b strings.Builder
	b.WriteString(overlayHeader)
	fmt.Fprintf(&b, "images:\n- location: %s\n  arch: %s\n  digest: %s\n", quoteYAML(image.Location), quoteYAML(image.Arch), quoteYAML(image.Digest))
	// The published image deliberately carries no login account. Make Lima's
	// cloud-init user explicit instead of accepting the limactl host's username:
	// on remote Lima those are different machines, and therefore often different
	// names. Finalize must provision the same account that cloud-init creates.
	if cfg.User != "" {
		fmt.Fprintf(&b, "user:\n  name: %s\n", quoteYAML(cfg.User))
	}
	b.WriteString("mountType: reverse-sshfs\n")
	fmt.Fprintf(&b, "cpus: %d\n", cfg.CPUs)
	fmt.Fprintf(&b, "memory: %s\n", quoteYAML(cfg.Memory))
	fmt.Fprintf(&b, "disk: %s\n", quoteYAML(vm.BaseDiskFloor))
	b.WriteString(overlayContainerd)
	b.WriteString("mounts:\n")
	// The mount point comes from the constant, not a literal: this line is the
	// PRODUCER of the value lima.Client.Configure's jq selector has to match when
	// it repoints a clone's mount, and two literals would be one rename away from
	// silently disagreeing.
	fmt.Fprintf(&b, "- location: %s\n  mountPoint: %s\n  writable: false\n", quoteYAML(playbookDir), playbookMountPoint)
	b.WriteString(overlayProvision)
	return []byte(b.String()), nil
}

// renderLegacyBaseOverlay keeps the pre-image convergence path operational
// until that machinery is removed. Provider creates use RenderBaseOverlay.
func renderLegacyBaseOverlay(cfg vm.CreateConfig, playbookDir string) []byte {
	var b strings.Builder
	b.WriteString("# Legacy stock-image base for playbook convergence\nbase:\n- template:_images/debian-13\n")
	fmt.Fprintf(&b, "cpus: %d\n", cfg.CPUs)
	fmt.Fprintf(&b, "memory: %s\n", quoteYAML(cfg.Memory))
	fmt.Fprintf(&b, "disk: %s\n", quoteYAML(vm.BaseDiskFloor))
	b.WriteString(overlayContainerd)
	b.WriteString("mounts:\n")
	fmt.Fprintf(&b, "- location: %s\n  mountPoint: %s\n  writable: false\n", quoteYAML(playbookDir), playbookMountPoint)
	b.WriteString(overlayProvision)
	return []byte(b.String())
}

// quoteYAML renders s as a double-quoted YAML scalar, matching the original
// bash provisioner's yaml_str helper (escaping backslashes and double quotes).
func quoteYAML(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}
