package provision

import (
	"fmt"
	"strings"

	"github.com/lullabot/sandbar/internal/vm"
)

// overlayHeader is the fixed top of the base overlay: the generated-by banner
// and the inherited Debian 13 image template. It mirrors the original bash
// provisioner's render_base_overlay.
const overlayHeader = `# Generated by the Claude Code VM TUI — inherits the shipped Debian 13 image
# template so Lima manages image selection, arch, and caching. The default
# host-home mount is intentionally NOT inherited (these VMs run Claude
# unsupervised). The only mount is the playbook, read-only: there is NO writable
# host mount, so deleting a VM provably removes everything it produced. Move
# files in or out with the TUI's Upload/Download actions.
base:
- template:_images/debian-13
`

// overlayContainerd switches off Lima's own container stack. Lima defaults to
// installing the nerdctl-full bundle and running rootless containerd for the
// user, which is entirely redundant here: the playbook installs Docker, and
// that is the container runtime these VMs actually use.
//
// It is not free. Measured on a clone of the base (qemu/x86_64, 8 vCPU), Lima's
// containerd setup runs inside cloud-final on EVERY boot and costs ~19s of the
// ~58s `limactl start` — cloud-final alone drops from 13.3s to 3.5s with this
// off, and a clone's boot goes 58s -> 39s. It also plants ~575MB of nerdctl-full
// in /usr/local/bin of the BASE image, which every clone then copies.
//
// Lima's boot script skips the whole stage when both are false; docker.service
// is untouched (verified: docker info/ps still work on a base built this way).
const overlayContainerd = `containerd:
  system: false
  user: false
`

// overlayProvision is the fixed dependency provision script. It installs just
// enough (ansible-core, rsync, and a few apt prerequisites) for the
// playbook to be run later over `limactl shell`; the heavy playbook itself is
// NOT run here so its output can stream to the terminal. ansible-core (8MB
// installed) replaces Debian's fat `ansible` bundle (200MB installed) — the
// playbook is collection-free on the default path, so the bundle's vendored
// collections are unneeded — but passlib, which the bundle used to supply, has
// to be named explicitly because the user role's password_hash filter needs it.
// curl/gnupg/ca-certificates are installed here
// too so a later, single consolidated apt install has them already present.
const overlayProvision = `provision:
- mode: dependency
  script: |
    #!/bin/bash
    set -eux -o pipefail
    # Install just enough to run the playbook over ` + "`limactl shell`" + `; skip the
    # apt work once present so restarts stay fast. The playbook itself is run
    # separately (over a shell) so its output is visible. This script reruns on
    # every boot (including every clone's), so the guard must check for every
    # tool it installs or a stale check will leave later boots missing one.
    if command -v ansible-playbook >/dev/null 2>&1 \
       && command -v rsync >/dev/null 2>&1 \
       && command -v curl >/dev/null 2>&1 \
       && command -v gpg >/dev/null 2>&1 \
       && python3 -c 'import passlib' >/dev/null 2>&1; then
      exit 0
    fi
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    # --no-install-recommends is load-bearing, not hygiene: Debian's ansible-core
    # Recommends: ansible, so without it apt pulls the very 200MB collection
    # bundle (~436MB of ansible_collections on disk) that installing ansible-core
    # instead of ansible exists to avoid. Dropping this flag silently restores
    # the fat bundle and the slim-bootstrap win with it.
    #
    # python3-passlib is what --no-install-recommends costs us: the user role
    # hashes the generated account password with the password_hash('sha512')
    # filter, which imports passlib at runtime. The fat ansible bundle used to
    # pull it in as a Recommends, so dropping the bundle broke the play with
    # "Unable to encrypt nor hash, passlib must be installed". Name it
    # explicitly rather than leaning on another package's recommendation.
    apt-get install -y --no-install-recommends ansible-core rsync curl gnupg ca-certificates python3-passlib
`

// RenderBaseOverlay produces the Lima overlay YAML for the base image: the
// inherited Debian 13 template, cpus/memory/disk, a read-only mount of the
// playbook directory at /mnt/playbook, and the dependency provision script that
// installs ansible-core, rsync, and a few apt prerequisites. It mirrors the
// original bash provisioner's render_base_overlay.
//
// It deliberately does NOT mount a host apt-archive cache (that design was
// tried and backed out): Lima's mount type on a host without virtiofsd
// installed falls back to reverse-sshfs, and reverse-sshfs
// does not honour a guest chown of the mounted directory — `chown _apt
// /mnt/apt-cache/partial` fails with EPERM, which is fatal to apt's use of that
// directory as Dir::Cache::archives. virtiofsd is not bundled with Lima and is
// not guaranteed present on an arbitrary Linux host, so this is not a one-host
// fluke (Lima's reverse-sshfs default on macOS carries the same restriction).
// The apt cache is instead seeded/harvested via `limactl copy` around the base
// playbook run — see aptcache.go — which needs no host mount at all, so there
// is nothing here to strip from a clone. Client.Configure still strips any
// writable mount a clone inherits, as a standing guard against a future
// overlay change.
func RenderBaseOverlay(cfg vm.CreateConfig, playbookDir string) ([]byte, error) {
	var b strings.Builder
	b.WriteString(overlayHeader)
	fmt.Fprintf(&b, "cpus: %d\n", cfg.CPUs)
	fmt.Fprintf(&b, "memory: %s\n", quoteYAML(cfg.Memory))
	fmt.Fprintf(&b, "disk: %s\n", quoteYAML(vm.BaseDiskFloor))
	b.WriteString(overlayContainerd)
	b.WriteString("mounts:\n")
	fmt.Fprintf(&b, "- location: %s\n  mountPoint: /mnt/playbook\n  writable: false\n", quoteYAML(playbookDir))
	b.WriteString(overlayProvision)
	return []byte(b.String()), nil
}

// quoteYAML renders s as a double-quoted YAML scalar, matching the original
// bash provisioner's yaml_str helper (escaping backslashes and double quotes).
func quoteYAML(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}
